//! Docker Compose override generator and parser for worktree interoperability.
//!
//! Generates `docker-compose.claw.override.yml` to prevent container name
//! collisions and configure shared service/network interop.

use crate::core::config::DockerConfig;
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

/// A service parsed from a Compose YAML file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParsedService {
    pub name: String,
    pub container_name: Option<String>,
}

/// Parses service names and their container_name attributes from Compose YAML content.
///
/// # Example
///
/// ```
/// use git_claw::infra::docker::parse_compose_services;
///
/// let yaml = "services:\n  web:\n    container_name: my_web\n";
/// let services = parse_compose_services(yaml);
/// assert_eq!(services.len(), 1);
/// assert_eq!(services[0].name, "web");
/// assert_eq!(services[0].container_name.as_deref(), Some("my_web"));
/// ```
pub fn parse_compose_services(compose_content: &str) -> Vec<ParsedService> {
    let mut services = Vec::new();
    let mut in_services = false;
    let mut services_indent = 0;
    let mut current_service: Option<ParsedService> = None;
    let mut service_indent_level: Option<usize> = None;

    for line in compose_content.lines() {
        let trimmed_end = line.trim_end();
        if trimmed_end.is_empty() {
            continue;
        }
        let trimmed = trimmed_end.trim();
        if trimmed.starts_with('#') {
            continue;
        }

        let indent = line.len() - line.trim_start().len();

        if !in_services {
            if trimmed == "services:" || trimmed.starts_with("services:") {
                in_services = true;
                services_indent = indent;
            }
            continue;
        }

        // Check if we exited the services block
        if indent <= services_indent && !trimmed.is_empty() {
            in_services = false;
            if let Some(svc) = current_service.take() {
                services.push(svc);
            }
            continue;
        }

        // Inside services block:
        if let Some(expected_level) = service_indent_level {
            if indent == expected_level && trimmed.ends_with(':') {
                if let Some(svc) = current_service.take() {
                    services.push(svc);
                }
                let name = trimmed
                    .trim_end_matches(':')
                    .trim()
                    .trim_matches(|c| c == '\'' || c == '"');
                current_service = Some(ParsedService {
                    name: name.to_string(),
                    container_name: None,
                });
                continue;
            } else if indent > expected_level {
                if let Some(stripped) = trimmed.strip_prefix("container_name:") {
                    let val = stripped.trim().trim_matches(|c| c == '\'' || c == '"');
                    if let Some(ref mut svc) = current_service {
                        svc.container_name = Some(val.to_string());
                    }
                }
                continue;
            }
        }

        // First service encountered
        if indent > services_indent && trimmed.ends_with(':') {
            service_indent_level = Some(indent);
            let name = trimmed
                .trim_end_matches(':')
                .trim()
                .trim_matches(|c| c == '\'' || c == '"');
            current_service = Some(ParsedService {
                name: name.to_string(),
                container_name: None,
            });
        }
    }

    if let Some(svc) = current_service {
        services.push(svc);
    }

    services
}

/// Generates the content of `docker-compose.claw.override.yml`.
///
/// # Example
///
/// ```
/// use git_claw::core::config::DockerConfig;
/// use git_claw::infra::docker::{generate_override_content, ParsedService};
///
/// let config = DockerConfig {
///     compose_file: None,
///     network: Some("shared_net".to_string()),
///     shared_services: vec!["db".to_string()],
/// };
/// let services = vec![ParsedService {
///     name: "web".to_string(),
///     container_name: Some("web_app".to_string()),
/// }];
/// let content = generate_override_content(&services, &config);
/// assert!(content.contains("external: true"));
/// assert!(content.contains("container_name: null"));
/// ```
pub fn generate_override_content(services: &[ParsedService], config: &DockerConfig) -> String {
    let mut out = String::from("# Generated by git-claw\n");

    let shared_set: BTreeSet<&str> = config.shared_services.iter().map(|s| s.as_str()).collect();

    let mut service_lines = Vec::new();

    // 1. Shared services: disabled and neutralized
    for svc_name in &config.shared_services {
        service_lines.push(format!("  {svc_name}:"));
        service_lines.push("    container_name: null".to_string());
        service_lines.push("    profiles:".to_string());
        service_lines.push("      - claw-disabled".to_string());
        service_lines.push("    restart: \"no\"".to_string());
        service_lines.push("    scale: 0".to_string());
        service_lines.push("    entrypoint: [\"true\"]".to_string());
    }

    // 2. Worktree-specific services that need container_name neutralization or network attachment
    for svc in services {
        if shared_set.contains(svc.name.as_str()) {
            continue;
        }

        let needs_neutralization = svc.container_name.is_some();
        let needs_network = config.network.is_some();

        if needs_neutralization || needs_network {
            service_lines.push(format!("  {}:", svc.name));
            if needs_neutralization {
                service_lines.push("    container_name: null".to_string());
            }
            if let Some(ref net) = config.network {
                service_lines.push("    networks:".to_string());
                service_lines.push(format!("      - {net}"));
            }
        }
    }

    if !service_lines.is_empty() {
        out.push_str("services:\n");
        for line in service_lines {
            out.push_str(&line);
            out.push('\n');
        }
    }

    // Networks
    if let Some(ref net) = config.network {
        out.push_str("networks:\n");
        out.push_str(&format!("  {net}:\n"));
        out.push_str("    external: true\n");
    }

    out
}

/// Generates `docker-compose.claw.override.yml` in the given worktree directory
/// if Docker configuration is enabled.
///
/// Returns `Ok(Some(path))` if generated, or `Ok(None)` if Docker configuration is disabled.
///
/// # Example
///
/// ```
/// use git_claw::core::config::DockerConfig;
/// use git_claw::infra::docker::generate_docker_compose_override;
/// use tempfile::tempdir;
///
/// let dir = tempdir().unwrap();
/// let config = DockerConfig {
///     compose_file: None,
///     network: Some("net".to_string()),
///     shared_services: vec!["postgres".to_string()],
/// };
/// let result = generate_docker_compose_override(dir.path(), dir.path(), &config).unwrap();
/// assert!(result.is_some());
/// ```
pub fn generate_docker_compose_override(
    toplevel_path: &Path,
    worktree_path: &Path,
    config: &DockerConfig,
) -> Result<Option<PathBuf>, std::io::Error> {
    if !config.is_enabled() {
        return Ok(None);
    }

    let candidates = [
        "docker-compose.yml",
        "docker-compose.yaml",
        "compose.yml",
        "compose.yaml",
    ];

    let compose_path = if let Some(ref custom_file) = config.compose_file {
        let p = worktree_path.join(custom_file);
        if p.exists() {
            Some(p)
        } else {
            let top_p = toplevel_path.join(custom_file);
            if top_p.exists() {
                Some(top_p)
            } else {
                None
            }
        }
    } else {
        candidates
            .iter()
            .map(|name| worktree_path.join(name))
            .find(|p| p.exists())
            .or_else(|| {
                candidates
                    .iter()
                    .map(|name| toplevel_path.join(name))
                    .find(|p| p.exists())
            })
    };

    let services = if let Some(ref p) = compose_path {
        let content = fs::read_to_string(p).unwrap_or_default();
        parse_compose_services(&content)
    } else {
        Vec::new()
    };

    let content = generate_override_content(&services, config);
    let target = worktree_path.join("docker-compose.claw.override.yml");
    fs::write(&target, &content)?;

    // If custom compose_file is in a subdirectory, also write it in that subdirectory
    if let Some(ref custom_file) = config.compose_file {
        if let Some(parent) = Path::new(custom_file).parent() {
            if parent != Path::new("") {
                let sub_target = worktree_path
                    .join(parent)
                    .join("docker-compose.claw.override.yml");
                let _ = fs::write(sub_target, &content);
            }
        }
    }

    Ok(Some(target))
}
